f=open("myfile.txt","w")
f.write("Hello")
f.write("Name")
f.close()
file=open("myfile.txt","rb")
print(file)
file=open("myfile.txt","wb")
print("Name of the file:",file.name)
file.close()
print("File is closed:",file.closed)
print("File has been opened in", file.mode,"mode")
f=open("myfile.txt","r")
print(f.read())
f=open("myfile.txt","r")
print(f.readline())
f=open("myfile.txt","w")
f.write("My name is ANugrah")
f.write("UPES")
f.write("He is the topper of BTECH CSE")
f.close()
f=open("myfile.txt","r")
print(f.readline())



